
const 	folders = [{ id:0,
		theroots:"		00roots"	,
		thebole:"		01bole"	,
		thebeams:"		02beams"	,
		thebraches:"	03branches"	,
		theleaves:"		04leaves"	,
		thefruit:"		05fruit"	,
		}]
const 	folder = folders[0];

const 	levels = [{ id:0,
		level00:	"/"									,
		level01:	"../"								,
		level02:	"../../"							,
		level03:	"../../../"							,
		level04:	"../../../../"						,
		level05:	"../../../../../"					,
		level06:	"../../../../../../"				,
		level07:	"../../../../../../../"				,
		level08:	"../../../../../../../../"			,
		level09:	"../../../../../../../../../"		,
		level10:	"../../../../../../../../../../"	
		}] 
const 	level = levels[0];
const 	commonnames = [{ id:0,
		webp:	".html"		,
		photo:	".jpg"		,
		}]
const 	commname = commonnames[0];
const 	sitelocations = [{ id:0,
		tree:		level.level00			,
		seeds:		"mhpack/"				,
		theroots:	"mhpack/00roots/"		, therootsimgs:	"mhpack/00roots/00rootsimgs/"	,
		thebole:	"mhpack/01thebole/"		,
		beams:		"mhpack/02beams/"		,
		branches:	"mhpack/03branches/"	,
		leaves:		"mhpack/04leaves/"		,
		fruit:		"mhpack/05fruit/"		,
		//////////////////
		door01:		"mhpack/tribe01/"	,
		door02:		"mhpack/tribe02/"	,
		door03:		"mhpack/tribe03/"	,
		door04:		"mhpack/tribe04/"	,
		door05:		"mhpack/tribe05/"	
		}]
const 	locat = sitelocations[0];
const 	indeximagefiles = [{ id:0,
		img00:	"01rootsimg00.jpg"	, icon00:	"02rootsicon00.jpg"	,
		img01:	"01rootsimg01.jpg"	, icon01:	"02rootsicon01.jpg"	,
		img02:	"01rootsimg02.jpg"	, 
		img03:	"01rootsimg03.jpg"	,
		img04:	"01rootsimg04.jpg"	,
		img05:	"01rootsimg05.jpg"	,
		img06:	"01rootsimg06.jpg"	,
		img07:	"01rootsimg07.jpg"	,
		img08:	"01rootsimg08.jpg"	,
		img09:	"01rootsimg09.jpg"	,
		img10:	"01rootsimg10.jpg"	,
		img11:	"01rootsimg11.jpg"	,
		img12:	"01rootsimg12.jpg"	,
		img13:	"01rootsimg13.jpg"	,
		img14:	"01rootsimg14.jpg"	,
		img15:	"01rootsimg15.jpg"	,
		img16:	"01rootsimg16.jpg"	,
		img17:	"01rootsimg17.jpg"	,
		img18:	"01rootsimg18.jpg"	,
		img19:	"01rootsimg19.jpg"	,
		img20:	"01rootsimg20.jpg"	,
		img21:	"01rootsimg21.jpg"	,
		}]
const 	indeximgfile = indeximagefiles[0];
const 	indeximages = [{ id:0,
		img00:	locat.therootsimgs+indeximgfile.img00	, icon00:	locat.theroots+indeximgfile.icon00	,
		img01:	locat.therootsimgs+indeximgfile.img01	,
		img02:	locat.therootsimgs+indeximgfile.img02	,
		img03:	locat.therootsimgs+indeximgfile.img03	,
		img04:	locat.therootsimgs+indeximgfile.img04	,
		img05:	locat.therootsimgs+indeximgfile.img05	,
		img06:	locat.therootsimgs+indeximgfile.img06	,
		img07:	locat.therootsimgs+indeximgfile.img07	,
		img08:	locat.therootsimgs+indeximgfile.img08	,
		img09:	locat.therootsimgs+indeximgfile.img09	,
		img10:	locat.therootsimgs+indeximgfile.img10	,
		img11:	locat.therootsimgs+indeximgfile.img11	,
		img12:	locat.therootsimgs+indeximgfile.img12	,
		img13:	locat.therootsimgs+indeximgfile.img13	,
		img14:	locat.therootsimgs+indeximgfile.img14	,
		img15:	locat.therootsimgs+indeximgfile.img15	,
		img16:	locat.therootsimgs+indeximgfile.img16	,
		img17:	locat.therootsimgs+indeximgfile.img17	,
		img18:	locat.therootsimgs+indeximgfile.img18	,
		img19:	locat.therootsimgs+indeximgfile.img19	,
		img20:	locat.therootsimgs+indeximgfile.img20	,
		img21:	locat.therootsimgs+indeximgfile.img21	,
		}]
const 	indeximg = indeximages[0];
